-- ============================================================
-- Boquitas Sanas - esquema PostgreSQL normalizado
-- IDs autoincrementales (BIGINT / IDENTITY)
-- ============================================================
-- Ejecutar en Supabase > SQL Editor sobre una base de datos vacía.
-- IMPORTANTE: este script elimina las tablas del esquema anterior
-- para recrearlas con IDs numéricos autoincrementales.
-- ============================================================

DROP TABLE IF EXISTS citas CASCADE;
DROP TABLE IF EXISTS horarios_disponibles CASCADE;
DROP TABLE IF EXISTS servicios CASCADE;
DROP TABLE IF EXISTS pacientes CASCADE;
DROP TABLE IF EXISTS usuarios CASCADE;
DROP TABLE IF EXISTS estado_cita CASCADE;
DROP TABLE IF EXISTS estado_horario CASCADE;
DROP TABLE IF EXISTS rol_usuario CASCADE;

-- ============================================================
-- CATÁLOGOS
-- ============================================================

CREATE TABLE rol_usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(30) NOT NULL UNIQUE,
    nombre VARCHAR(80) NOT NULL
);

CREATE TABLE estado_horario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(30) NOT NULL UNIQUE,
    nombre VARCHAR(80) NOT NULL
);

CREATE TABLE estado_cita (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(30) NOT NULL UNIQUE,
    nombre VARCHAR(80) NOT NULL
);

-- ============================================================
-- DATOS INICIALES DE CATÁLOGOS
-- ============================================================

INSERT INTO rol_usuario (codigo, nombre) VALUES
    ('ADMIN', 'Administrador'),
    ('ODONTOLOGO', 'Odontólogo'),
    ('SECRETARIA', 'Secretaria');

INSERT INTO estado_horario (codigo, nombre) VALUES
    ('DISPONIBLE', 'Disponible'),
    ('OCUPADO', 'Ocupado'),
    ('BLOQUEADO', 'Bloqueado');

INSERT INTO estado_cita (codigo, nombre) VALUES
    ('PENDIENTE', 'Pendiente'),
    ('EN_ESPERA', 'En espera'),
    ('ATENDIDA', 'Atendida'),
    ('CANCELADA', 'Cancelada');

-- ============================================================
-- USUARIOS
-- ============================================================

CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cedula VARCHAR(10) NOT NULL UNIQUE,
    nombres VARCHAR(100) NOT NULL,
    apellidos VARCHAR(100) NOT NULL,
    email VARCHAR(150) UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    rol_usuario_id BIGINT NOT NULL REFERENCES rol_usuario(id),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- PACIENTES
-- ============================================================

CREATE TABLE pacientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cedula VARCHAR(10) NOT NULL UNIQUE,
    nombres VARCHAR(100) NOT NULL,
    apellidos VARCHAR(100) NOT NULL,
    telefono VARCHAR(30),
    email VARCHAR(150),
    fecha_nacimiento DATE,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- SERVICIOS
-- ============================================================

CREATE TABLE servicios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    precio NUMERIC(12,2) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

-- ============================================================
-- HORARIOS
-- ============================================================

CREATE TABLE horarios_disponibles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    odontologo_id BIGINT NOT NULL REFERENCES usuarios(id),
    fecha DATE NOT NULL,
    hora_inicio TIME NOT NULL,
    hora_fin TIME NOT NULL,
    estado_horario_id BIGINT NOT NULL REFERENCES estado_horario(id),
    creado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_horario_horas CHECK (hora_inicio < hora_fin)
);

-- ============================================================
-- CITAS
-- ============================================================

CREATE TABLE citas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id BIGINT NOT NULL REFERENCES pacientes(id),
    odontologo_id BIGINT REFERENCES usuarios(id),
    horario_id BIGINT NOT NULL UNIQUE REFERENCES horarios_disponibles(id),
    servicio_id BIGINT REFERENCES servicios(id),
    estado_cita_id BIGINT NOT NULL REFERENCES estado_cita(id),
    notas TEXT,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- ÍNDICES
-- ============================================================

CREATE INDEX idx_usuarios_rol_id
    ON usuarios(rol_usuario_id);

CREATE INDEX idx_horarios_odontologo_fecha
    ON horarios_disponibles(odontologo_id, fecha);

CREATE INDEX idx_horarios_fecha_estado
    ON horarios_disponibles(fecha, estado_horario_id);

CREATE INDEX idx_citas_paciente
    ON citas(paciente_id);

CREATE INDEX idx_citas_odontologo
    ON citas(odontologo_id);

CREATE INDEX idx_citas_estado
    ON citas(estado_cita_id);

-- ============================================================
-- DOCUMENTACIÓN
-- ============================================================

COMMENT ON TABLE rol_usuario IS 'Catálogo normalizado de roles de usuarios.';
COMMENT ON TABLE estado_horario IS 'Catálogo normalizado de estados de horarios.';
COMMENT ON TABLE estado_cita IS 'Catálogo normalizado de estados de citas.';
COMMENT ON COLUMN usuarios.password_hash IS 'Contraseña almacenada mediante BCrypt; nunca texto plano.';
